"""Generate SECURITY_REPORT.md from a SecurityReport."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from reporium_security.scanner import SecurityReport


def _grade_emoji(grade: str) -> str:
    """Return a text indicator for the grade."""
    indicators = {
        "A": "PASS",
        "B": "PASS (minor)",
        "C": "WARN",
        "D": "FAIL",
        "F": "CRITICAL",
    }
    return indicators.get(grade, "UNKNOWN")


def generate_report(report: SecurityReport) -> str:
    """Generate markdown content for a SECURITY_REPORT.md."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# Security Report: {report.repo_name}",
        "",
        f"**Grade: {report.grade}** ({_grade_emoji(str(report.grade))})",
        f"**Scanned:** {timestamp}",
        "",
        "---",
        "",
        "## Secrets Check",
        "",
    ]

    if report.secrets.passed:
        lines.append("No secrets detected in source files.")
    else:
        lines.append(f"**{len(report.secrets.findings)} issue(s) found:**")
        lines.append("")
        for finding in report.secrets.findings:
            lines.append(
                f"- `{finding.file}` line {finding.line_number}: "
                f"{finding.pattern_name}"
            )

    lines.extend(["", "## Dependency CVE Check", ""])

    if report.dependencies.skipped:
        lines.append(f"Skipped: {report.dependencies.skip_reason}")
    elif report.dependencies.passed:
        lines.append("No known CVEs found in dependencies.")
    else:
        lines.append(f"**{len(report.dependencies.findings)} CVE(s) found:**")
        lines.append("")
        for finding in report.dependencies.findings:
            lines.append(
                f"- **{finding.severity}** `{finding.package}=={finding.version}`: "
                f"{finding.vulnerability_id}"
            )

    lines.extend(["", "## Workflow Security Check", ""])

    if report.workflows.passed:
        lines.append("All workflows follow security best practices.")
    else:
        lines.append(f"**{len(report.workflows.findings)} issue(s) found:**")
        lines.append("")
        for finding in report.workflows.findings:
            lines.append(
                f"- [{finding.severity.upper()}] `{finding.file}`: {finding.issue}"
            )

    lines.extend(["", "## Sensitive File Check", ""])

    if report.files.passed:
        lines.append("No sensitive files detected in the repository.")
    else:
        lines.append(f"**{len(report.files.findings)} issue(s) found:**")
        lines.append("")
        for finding in report.files.findings:
            lines.append(f"- `{finding.file}`: {finding.reason}")

    lines.extend(["", "## Git History Check", ""])

    if report.history.skipped:
        lines.append(f"Skipped: {report.history.skip_reason}")
    elif report.history.passed:
        lines.append("No secrets detected in recent git history.")
    else:
        lines.append(f"**{len(report.history.findings)} issue(s) found:**")
        lines.append("")
        for finding in report.history.findings:
            lines.append(
                f"- Commit `{finding.commit}`: {finding.pattern_name}"
            )

    lines.extend(["", "---", "", f"*Generated by reporium-security*", ""])

    return "\n".join(lines)


def write_report(report: SecurityReport, output_path: Path | None = None) -> Path:
    """Write SECURITY_REPORT.md to disk."""
    if output_path is None:
        output_path = Path("SECURITY_REPORT.md")

    content = generate_report(report)
    output_path.write_text(content, encoding="utf-8")
    return output_path
